### ISSUE TITLE
Laravel 11 Upgrade

### ISSUE THREAD

**Issue by RelBreR** [laravel-notification-channels/rocket-chat#22]
Can you please upgrade the package to Laravel 11. There are no other viable libraries for RocketChat and the app I'm building is breaking. This kind gentleman has already made a pull request [Here](https://github.com/laravel-notification-channels/rocket-chat/pull/21). Much appreciated

**Comment by Funfare** [comment]
Pull request is merged and new release 0.6.0 created :)
