### ISSUE TITLE
Do we really need clearAttachments method?

### ISSUE THREAD

**Issue by antonkomarev** [laravel-notification-channels/rocket-chat#8]
@Funfare you've [added](https://github.com/laravel-notification-channels/rocket-chat/pull/3/files#r382906271) `clearAttachments` method to `RocketChatMessage` class.
What is the use case? Do we really need it?

**Comment by Funfare** [comment]
Without that there is no option to change/reset the attachments.
Don't know of we really ned that, but for me it is bad design when you can't change an attribute later. All other methods could be called several times

**Comment by antonkomarev** [comment]
I don't think it's bad design. As for me it looks really wrong when you are attaching files to message and then decide to remove all of them. That means you've missed some kind of conditional before attachments add process.

**Comment by Funfare** [comment]
ok. Then I think we can remove that method
